#! /bin/sh
#
# skeleton	example file to build /etc/init.d/ scripts.
#		This file should be used to construct scripts for /etc/init.d.
#
#		Written by Miquel van Smoorenburg <miquels@cistron.nl>.
#		Modified for Debian
#		by Ian Murdock <imurdock@gnu.ai.mit.edu>.
#               Further changes by Javier Fernandez-Sanguino <jfs@debian.org>
#
# Version:	@(#)skeleton  1.9  26-Feb-2001  miquels@cistron.nl
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=i2c_comm

# I2C devices
device0="user-eeprom"
device1="serial-eeprom"
device2="module-eeprom"
device6="i2c-raw"
 
mode="666"
group="root"
path="/dev"
kernel=`uname -r`
module_path="/lib/modules/$kernel/kernel/drivers/extra/i2c_comm"

case "$1" in
    start)
# Remove stale nodes and replace them, then give gid and perms
    rm -f $path/$device0
    rm -f $path/$device1
    rm -f $path/$device2
    rm -f $path/$device6

    # Check that module is really loaded
    lsmod | grep -q $NAME

    if [ $? -ne 0 ] ; then
	modprobe $NAME
    fi

    # retrieve major number
    major=$(awk "\$2==\"$NAME\" {print \$1}" /proc/devices)

    mknod $path/$device0 c $major 0
    mknod $path/$device1 c $major 1
    mknod $path/$device2 c $major 2
    mknod $path/$device6 c $major 6

    chgrp $group $path/$device0
    chmod $mode  $path/$device0
    chgrp $group $path/$device1
    chmod $mode  $path/$device1
    chgrp $group $path/$device2
    chmod $mode  $path/$device2
    chgrp $group $path/$device6
    chmod $mode  $path/$device6
    ;;

    # These here are just to make script LSB compliant (hopefully!)
    stop)    
    B=1
    ;;

    restart)
    B=2
    ;;

    force-reload)
    B=3
    ;;

    force-stop)
    B=4
    ;;

    *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start}" >&2
    exit 1
    ;;
esac

exit 0
